run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

# Settings divided into groups of 10
settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing a gray suit, in a glass office with views of high-rise buildings."
      - "who is 30 years old, with short hair, wearing a gray suit, on a rooftop terrace overlooking skyscrapers."
      - "who is 30 years old, with short hair, wearing a gray suit, at a desk by windows with views of tall buildings."
      - "who is 30 years old, with short hair, wearing a gray suit, in a glass hallway with urban skyline vistas."
      - "who is 30 years old, with short hair, wearing a gray suit, by a window with a view of towering skyscrapers."
      - "who is 30 years old, with short hair, wearing a gray suit, in a top-floor lobby with panoramic skyline views."
      - "who is 30 years old, with short hair, wearing a gray suit, in a glass-walled conference room overlooking high-rises."
      - "who is 30 years old, with short hair, wearing a gray suit, in a glass elevator with views of surrounding skyscrapers."
      - "who is 30 years old, with short hair, wearing a gray suit, at a reception with panoramic windows showing tall buildings."
      - "who is 30 years old, with short hair, wearing a gray suit, in a break room with views of the city's skyscrapers."

  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing charcoal suit, in a glass boardroom with views of high-rise buildings."
      - "who is 30 years old, with short hair, wearing charcoal suit, in a glass-walled office area overlooking skyscrapers."
      - "who is 30 years old, with short hair, wearing charcoal suit, in a glass corridor with views of tall buildings."
      - "who is 30 years old, with short hair, wearing charcoal suit, at a copier by windows showing the urban skyline."
      - "who is 30 years old, with short hair, wearing charcoal suit, in a meeting room with views of towering skyscrapers."
      - "who is 30 years old, with short hair, wearing charcoal suit, at a desk facing glass walls with high-rise views."
      - "who is 30 years old, with short hair, wearing charcoal suit, in a glass atrium with panoramic city skyline views."
      - "who is 30 years old, with short hair, wearing charcoal suit, in a lounge with windows showing surrounding skyscrapers."
      - "who is 30 years old, with short hair, wearing charcoal suit, in a glass-walled pantry overlooking tall buildings."
      - "who is 30 years old, with short hair, wearing charcoal suit, in a conference room with views of high-rise buildings."

out_dir: "condition_1/5_glass"
clip_threshold: 0.28
