run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"
# Settings divided into groups of 10
settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing a gray suit, standing in an office"
      - "who is 30 years old, with short hair, wearing a gray suit, posed in front of office desks"
      - "who is 30 years old, with short hair, wearing a gray suit, standing in an office hallway"
      - "who is 30 years old, with short hair, wearing a gray suit, in front of office cubicles"
      - "who is 30 years old, with short hair, wearing a gray suit, standing by office windows"
      - "who is 30 years old, with short hair, wearing a gray suit, posed in an office lobby"
      - "who is 30 years old, with short hair, wearing a gray suit, standing near office equipment"
      - "who is 30 years old, with short hair, wearing a gray suit, in an office doorway"
      - "who is 30 years old, with short hair, wearing a gray suit, standing by office bookshelves"
      - "who is 30 years old, with short hair, wearing a gray suit, posed in a conference room"

  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing a charcoal suit, standing in an office area"
      - "who is 30 years old, with short hair, wearing a charcoal suit, posed by office file cabinets"
      - "who is 30 years old, with short hair, wearing a charcoal suit, standing near office plants"
      - "who is 30 years old, with short hair, wearing a charcoal suit, in front of an office whiteboard"
      - "who is 30 years old, with short hair, wearing a charcoal suit, standing by office water cooler"
      - "who is 30 years old, with short hair, wearing a charcoal suit, posed in an office break room"
      - "who is 30 years old, with short hair, wearing a charcoal suit, standing near office elevator"
      - "who is 30 years old, with short hair, wearing a charcoal suit, in an office reception area"
      - "who is 30 years old, with short hair, wearing a charcoal suit, standing by office artwork"
      - "who is 30 years old, with short hair, wearing a charcoal suit, posed in an office corridor"

out_dir: "condition_1/2_office"
clip_threshold: 0.28
