run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing golf attire, practicing swing technique"
      - "who is 30 years old, with short hair, wearing golf attire, teeing off at first hole"
      - "who is 30 years old, with short hair, wearing golf attire, putting on green"
      - "who is 30 years old, with short hair, wearing golf attire, checking course layout"
      - "who is 30 years old, with short hair, wearing golf attire, selecting club from bag"
      - "who is 30 years old, with short hair, wearing golf attire, lining up shot"
      - "who is 30 years old, with short hair, wearing golf attire, walking fairway"
      - "who is 30 years old, with short hair, wearing golf attire, at driving range"
      - "who is 30 years old, with short hair, wearing golf attire, reading green slope"
      - "who is 30 years old, with short hair, wearing golf attire, preparing for shot"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing golf attire, practicing at putting green"
      - "who is 30 years old, with short hair, wearing golf attire, approaching golf ball"
      - "who is 30 years old, with short hair, wearing golf attire, watching ball trajectory"
      - "who is 30 years old, with short hair, wearing golf attire, on course with caddie"
      - "who is 30 years old, with short hair, wearing golf attire, measuring shot distance"
      - "who is 30 years old, with short hair, wearing golf attire, at golf practice area"
      - "who is 30 years old, with short hair, wearing golf attire, checking wind direction"
      - "who is 30 years old, with short hair, wearing golf attire, in golf cart"
      - "who is 30 years old, with short hair, wearing golf attire, near sand bunker"
      - "who is 30 years old, with short hair, wearing golf attire, finishing swing follow-through"

out_dir: "condition_4/4"
clip_threshold: 0.28
