run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing hiking gear, adjusting backpack on a mountain trail"
      - "who is 30 years old, with short hair, wearing hiking gear, checking trail map in the forest"
      - "who is 30 years old, with short hair, wearing hiking gear, taking a water break on a woodland path"
      - "who is 30 years old, with short hair, wearing hiking gear, crossing a forest bridge"
      - "who is 30 years old, with short hair, wearing hiking gear, climbing rocky terrain"
      - "who is 30 years old, with short hair, wearing hiking gear, photographing nature on a trail"
      - "who is 30 years old, with short hair, wearing hiking gear, navigating through forest paths"
      - "who is 30 years old, with short hair, wearing hiking gear, resting at a trail viewpoint"
      - "who is 30 years old, with short hair, wearing hiking gear, trekking through wilderness"
      - "who is 30 years old, with short hair, wearing hiking gear, exploring mountain trails"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing hiking gear, setting up trekking poles"
      - "who is 30 years old, with short hair, wearing hiking gear, checking compass on forest path"
      - "who is 30 years old, with short hair, wearing hiking gear, ascending steep trail sections"
      - "who is 30 years old, with short hair, wearing hiking gear, crossing mountain streams"
      - "who is 30 years old, with short hair, wearing hiking gear, observing wildlife from trail"
      - "who is 30 years old, with short hair, wearing hiking gear, adjusting hiking boots"
      - "who is 30 years old, with short hair, wearing hiking gear, walking through pine forest"
      - "who is 30 years old, with short hair, wearing hiking gear, following marked trails"
      - "who is 30 years old, with short hair, wearing hiking gear, hiking scenic mountain paths"
      - "who is 30 years old, with short hair, wearing hiking gear, exploring wilderness trails"

out_dir: "condition_4/1"
clip_threshold: 0.28
