run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing workout clothes, running on track with proper form"
      - "who is 30 years old, with short hair, wearing workout clothes, sprinting on athletic track"
      - "who is 30 years old, with short hair, wearing workout clothes, jogging around stadium track"
      - "who is 30 years old, with short hair, wearing workout clothes, training on running track"
      - "who is 30 years old, with short hair, wearing workout clothes, practicing track running"
      - "who is 30 years old, with short hair, wearing workout clothes, exercising on outdoor track"
      - "who is 30 years old, with short hair, wearing workout clothes, maintaining running pace"
      - "who is 30 years old, with short hair, wearing workout clothes, doing track workouts"
      - "who is 30 years old, with short hair, wearing workout clothes, running track intervals"
      - "who is 30 years old, with short hair, wearing workout clothes, completing track laps"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing workout clothes, warming up on track"
      - "who is 30 years old, with short hair, wearing workout clothes, focusing on running form"
      - "who is 30 years old, with short hair, wearing workout clothes, training for track events"
      - "who is 30 years old, with short hair, wearing workout clothes, running track circuits"
      - "who is 30 years old, with short hair, wearing workout clothes, practicing sprint technique"
      - "who is 30 years old, with short hair, wearing workout clothes, exercising at stadium"
      - "who is 30 years old, with short hair, wearing workout clothes, doing track training"
      - "who is 30 years old, with short hair, wearing workout clothes, running track segments"
      - "who is 30 years old, with short hair, wearing workout clothes, maintaining track pace"
      - "who is 30 years old, with short hair, wearing workout clothes, completing running drills"

out_dir: "condition_4/3"
clip_threshold: 0.28
