run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing a light jacket, leaning on railing with cityscape"
      - "who is 30 years old, with short hair, wearing a light jacket, by railing overlooking city"
      - "who is 30 years old, with short hair, wearing a light jacket, against city view railing"
      - "who is 30 years old, with short hair, wearing a light jacket, at urban observation point"
      - "who is 30 years old, with short hair, wearing a light jacket, resting on city overlook"
      - "who is 30 years old, with short hair, wearing a light jacket, by downtown viewpoint"
      - "who is 30 years old, with short hair, wearing a light jacket, leaning at city railing"
      - "who is 30 years old, with short hair, wearing a light jacket, against skyline barrier"
      - "who is 30 years old, with short hair, wearing a light jacket, at city viewing spot"
      - "who is 30 years old, with short hair, wearing a light jacket, by metropolitan railing"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing a light jacket, overlooking urban scene"
      - "who is 30 years old, with short hair, wearing a light jacket, at city observation deck"
      - "who is 30 years old, with short hair, wearing a light jacket, leaning by city view"
      - "who is 30 years old, with short hair, wearing a light jacket, against urban railing"
      - "who is 30 years old, with short hair, wearing a light jacket, at skyline viewpoint"
      - "who is 30 years old, with short hair, wearing a light jacket, by city overlook railing"
      - "who is 30 years old, with short hair, wearing a light jacket, at urban viewing rail"
      - "who is 30 years old, with short hair, wearing a light jacket, leaning on city barrier"
      - "who is 30 years old, with short hair, wearing a light jacket, by downtown railing"
      - "who is 30 years old, with short hair, wearing a light jacket, at metropolitan viewpoint"

out_dir: "condition_6/4"
clip_threshold: 0.28
