run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing a suit, sitting professionally in office chair"
      - "who is 30 years old, with short hair, wearing a suit, seated at office desk"
      - "who is 30 years old, with short hair, wearing a suit, working in office chair"
      - "who is 30 years old, with short hair, wearing a suit, positioned in ergonomic chair"
      - "who is 30 years old, with short hair, wearing a suit, sitting with neutral expression"
      - "who is 30 years old, with short hair, wearing a suit, seated comfortably in chair"
      - "who is 30 years old, with short hair, wearing a suit, working at desk chair"
      - "who is 30 years old, with short hair, wearing a suit, sitting upright in office"
      - "who is 30 years old, with short hair, wearing a suit, positioned at workstation"
      - "who is 30 years old, with short hair, wearing a suit, seated professionally"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing a suit, sitting calmly in office"
      - "who is 30 years old, with short hair, wearing a suit, working at office setup"
      - "who is 30 years old, with short hair, wearing a suit, seated at workspace"
      - "who is 30 years old, with short hair, wearing a suit, positioned in work chair"
      - "who is 30 years old, with short hair, wearing a suit, sitting focused at desk"
      - "who is 30 years old, with short hair, wearing a suit, working professionally"
      - "who is 30 years old, with short hair, wearing a suit, seated with composure"
      - "who is 30 years old, with short hair, wearing a suit, positioned at desk"
      - "who is 30 years old, with short hair, wearing a suit, sitting attentively"
      - "who is 30 years old, with short hair, wearing a suit, working at station"

out_dir: "condition_6/2"
clip_threshold: 0.28
