run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, painting canvas"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, mixing colors"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, sketching artwork"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, preparing art supplies"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, cleaning brushes"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, setting up easel"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, organizing art tools"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, working on artwork"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, applying paint"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, arranging studio"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, creating artwork"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, blending colors"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, preparing canvas"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, using art materials"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, studying composition"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, adding details"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, reviewing artwork"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, organizing palette"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, adjusting lighting"
      - "who is 30 years old, with short hair, wearing a paint-splattered smock, finishing piece"

out_dir: "condition_5/5"
clip_threshold: 0.28
