run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "${HAIR_CONCEPT}"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a yoga pose on a mat, with a water bottle nearby, in a dimly lit living room"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, sitting in a quiet meditation, eyes closed, in a peaceful home office"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, meditating in lotus position, with incense burning nearby, in a serene bedroom"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, practicing mindfulness in a cross-legged position, surrounded by indoor plants"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, balancing in tree pose, on a meditation cushion, by a large window in a study"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, practicing deep breathing exercises, with a singing bowl in front, in a cozy attic"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a meditative walking pose, focused on each step, in a spacious hallway"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a cat pose on a yoga mat in a sunlit spare room"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, sitting cross-legged, with a singing bowl in hand, on a meditation cushion in a corner nook"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, practicing guided imagery meditation, relaxed posture, in a serene indoor sunroom"
  group_2:
    settings:
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in cobra pose on a yoga mat, with a water bottle nearby, by a fireplace in a living room"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a meditative state, hands resting on knees, in a tranquil indoor garden room"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, practicing silent meditation, eyes softly closed, in a serene conservatory at sunrise"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a contemplative pose, focusing on breath, in a minimalist meditation room"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, using a singing bowl, with meditation beads nearby, sitting on a windowsill in a cozy apartment"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, balancing in crow pose, with a yoga towel nearby, on a hardwood floor in a home yoga studio"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, practicing pranayama breathing, with a meditation app open, sitting on a cushion in a quiet bedroom"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a zen meditation pose, hands in cosmic mudra, in a Japanese-inspired indoor meditation space"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a mindful breathing exercise, seated comfortably, by an indoor water feature"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a transcendental meditation pose, eyes closed, in a peaceful attic space"
  group_3:
    settings:
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, balancing in crow pose, with a yoga towel nearby, on a hardwood floor in a home yoga studio"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, practicing pranayama breathing, with a meditation app open, sitting on a cushion in a quiet bedroom"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a zen meditation pose, hands in cosmic mudra, in a Japanese-inspired indoor meditation space"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a mindful breathing exercise, seated comfortably, by an indoor water feature"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, in a transcendental meditation pose, eyes closed, in a peaceful attic space"
out_dir: "condition_5/3_meditation"
clip_threshold: 0.28
