run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, cooking in a modern kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, preparing ingredients in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, using kitchen appliances"
      - "who is 30 years old, with short hair, wearing casual clothes, organizing kitchen counter"
      - "who is 30 years old, with short hair, wearing casual clothes, checking recipe in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, plating food in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, cleaning kitchen surfaces"
      - "who is 30 years old, with short hair, wearing casual clothes, arranging kitchen tools"
      - "who is 30 years old, with short hair, wearing casual clothes, measuring ingredients in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, washing dishes in kitchen"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, chopping vegetables in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, stirring pot in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, loading dishwasher in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, organizing pantry in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, brewing coffee in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, seasoning food in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, using microwave in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, setting kitchen timer"
      - "who is 30 years old, with short hair, wearing casual clothes, storing leftovers in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, wiping kitchen countertop"

out_dir: "condition_5/1"
clip_threshold: 0.28
