run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book in library"
      - "who is 30 years old, with short hair, wearing comfortable clothes, studying at library desk"
      - "who is 30 years old, with short hair, wearing comfortable clothes, searching library shelves"
      - "who is 30 years old, with short hair, wearing comfortable clothes, using library computer"
      - "who is 30 years old, with short hair, wearing comfortable clothes, organizing library materials"
      - "who is 30 years old, with short hair, wearing comfortable clothes, taking notes in library"
      - "who is 30 years old, with short hair, wearing comfortable clothes, browsing library collection"
      - "who is 30 years old, with short hair, wearing comfortable clothes, researching in library"
      - "who is 30 years old, with short hair, wearing comfortable clothes, checking out books"
      - "who is 30 years old, with short hair, wearing comfortable clothes, using library resources"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing comfortable clothes, working in quiet study area"
      - "who is 30 years old, with short hair, wearing comfortable clothes, accessing library database"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading in library corner"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reviewing library materials"
      - "who is 30 years old, with short hair, wearing comfortable clothes, using reference section"
      - "who is 30 years old, with short hair, wearing comfortable clothes, studying library documents"
      - "who is 30 years old, with short hair, wearing comfortable clothes, at library workstation"
      - "who is 30 years old, with short hair, wearing comfortable clothes, exploring library archives"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading periodicals"
      - "who is 30 years old, with short hair, wearing comfortable clothes, using library facilities"

out_dir: "condition_5/3"
clip_threshold: 0.28
