run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, cooking in a modern kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, preparing ingredients in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, cutting fruits in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, boiling soup in a pot"
      - "who is 30 years old, with short hair, wearing casual clothes, checking recipe in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, plating food in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, kneading a dough in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, plating dishes on a table"
      - "who is 30 years old, with short hair, wearing casual clothes, measuring ingredients in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, cutting vegetables in kitchen"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, slicing bread in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, grilling steak on a grill"
      - "who is 30 years old, with short hair, wearing casual clothes, boiling soup in a pot"
      - "who is 30 years old, with short hair, wearing casual clothes, simmering sauce on a stovein kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, kneading dough in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, marinating meat in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, putting vegetables on a pizza in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, whipping cream in a bowl in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, garnishing dishes with vegetables in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, cutting vegetables in kitchen"
  group_3:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, grating cheese and bread in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, peeling three potatoes in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, roasting vegetables in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, basting roast in kitchen"
      - "who is 30 years old, with short hair, wearing casual clothes, whisking eggs in a bowl with flour in kitchen"
out_dir: "condition_5/1_cooking"
clip_threshold: 0.28
