run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading hardcover novel in library"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading textbook at library desk"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book titles on library shelves"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading books on library computer"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading magazine articles in library"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading research papers in library's academic section"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book for book club discussion in library"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading 3D printing instructions in library"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book summaries on library's digital collection"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading genealogy records in library's special section"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading literary magazine in quiet cafe"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book for book club discussion in library"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading different book editions in personal study"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book transcript in book club meeting"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading graphic novel synopses in local bookstore"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book reviews for online literary community"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading poetry anthology in park"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book discussion questions during virtual book club"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading bookish content on social media platform"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book catalog on personal device"
  group_3:
    settings:
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading textbook in reading nook"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading book titles in personal library catalog"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading classic novel summaries in cozy den"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading bestseller quotes in book club meeting"
      - "who is 30 years old, with short hair, wearing comfortable clothes, reading literary criticism in academic journal"
out_dir: "condition_5/5_reading"
clip_threshold: 0.28
