run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, tuning acoustic guitar in living room"
      - "who is 30 years old, with short hair, wearing casual clothes, practicing piano scales in music room"
      - "who is 30 years old, with short hair, wearing casual clothes, learning new chord progressions in study"
      - "who is 30 years old, with short hair, wearing casual clothes, recording cover song in home studio"
      - "who is 30 years old, with short hair, wearing casual clothes, playing keyboard in music room"
      - "who is 30 years old, with short hair, wearing casual clothes, adjusting equalizer settings in control room"
      - "who is 30 years old, with short hair, wearing casual clothes, collaborating on songwriting via video call in home office"
      - "who is 30 years old, with short hair, wearing casual clothes, rehearsing bass lines in basement"
      - "who is 30 years old, with short hair, wearing casual clothes, exploring music production software in studio"
      - "who is 30 years old, with short hair, wearing casual clothes, playing keyboard in music room"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, practicing drum rudiments in garage"
      - "who is 30 years old, with short hair, wearing casual clothes, experimenting with synthesizer in loft"
      - "who is 30 years old, with short hair, wearing casual clothes, rehearsing bass lines in basement"
      - "who is 30 years old, with short hair, wearing casual clothes, exploring music production software in studio"
      - "who is 30 years old, with short hair, wearing casual clothes, playing keyboard in music room"
      - "who is 30 years old, with short hair, wearing casual clothes, testing different guitar pedals in practice space"
      - "who is 30 years old, with short hair, wearing casual clothes, recording podcast episode in makeshift booth"
      - "who is 30 years old, with short hair, wearing casual clothes, playing violin in a living room"
      - "who is 30 years old, with short hair, wearing casual clothes, setting up new audio interface in home studio"
      - "who is 30 years old, with short hair, wearing casual clothes, practicing piano scales in music room"
  group_3:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, recording vocal harmonies in soundproof booth"
      - "who is 30 years old, with short hair, wearing casual clothes, experimenting with loop pedal in practice room"
      - "who is 30 years old, with short hair, wearing casual clothes, composing melodies on ukulele in balcony"
      - "who is 30 years old, with short hair, wearing casual clothes, testing acoustic panels in recording space"
      - "who is 30 years old, with short hair, wearing casual clothes, exploring music production software in studio"


out_dir: "condition_5/4_music"
clip_threshold: 0.28
