run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.5
same_latent: false
style: "A photo of"
subject: "an young white man"
concept_token:
  - "young white man"
settings:
  - "Cozy home kitchen or living area, wearing an apron over casual clothes, mixing dough or baking cookies, measuring cups and flour nearby"
  - "Personal room or practice studio with soundproof walls, wearing a T-shirt and jeans, playing guitar or keyboard with headphones, sheet music stand"
  - "Stylish cafe interior, wearing casual knit top and skirt/jeans, reading a book or magazine, making notes and sipping coffee"
  - "Cinema lobby with movie posters on the wall, wearing a hoodie and jeans, holding popcorn and a drink, heading toward the screening room"
  - "Room with a gaming setup and LED lights, wearing a hoodie, jeans, and slippers, focused on an online game with a headset, RGB mouse and keyboard, drink nearby"
out_dir: "condition_5"
clip_threshold: 0.28
