run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "an white man"
concept_token:
  - "white man"
  - "30 years olds"
  - "short hair"
settings:
  - "who is 30 years old, with short hair, wearing a shirt in an office."
  - "who is 30 years old, with short hair, wearing a hoodie in a co-working lounge."
  - "who is 30 years old, with short hair, wearing a shirt in a cafe."
  - "who is 30 years old, with short hair, wearing a casual shirt in a meeting room."
out_dir: "condition_2"
clip_threshold: 0.28
