run_type: cached
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "an young white man"
concept_token:
  - "young white man"
  - "short hair"
settings:
  - "with short hair wearing an apron in a cozy kitchen with warm lighting."
  - "with short hair wearing a T-shirt and jeans in a soundproof practice room."
  - "with short hair wearing casual knit in a stylish cafe interior."
  - "with short hair wearing a hoodie and jeans in a cinema lobby with movie posters."
  - "with short hair wearing a hoodie, jeans, and slippers in a gaming room with LED lighting."
out_dir: "condition_5"
clip_threshold: 0.28
