run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.3
same_latent: false
style: "A photo of"
subject: "an young white man"
concept_token:
  - "young white man"
  - "short hair"
settings:
  - "with short hair wearing a casual T-shirt and pants on a rooftop with a city skyline."
  - "with short hair wearing a jacket and jeans in a cafe or lounge, not touching the drink."
  - "with short hair wearing light travel attire near a famous landmark, pointing or making a V sign."
  - "with short hair wearing casual clothes in front of a grand natural scenery, simply standing or looking."
  - "with short hair wearing a swimsuit and sunglasses on a beach sunbed, lightly holding a drink but not drinking."
  - "with short hair wearing a flashy swimsuit at an infinity pool, sitting by the edge with a cocktail glass, posing for the camera."
out_dir: "condition_6"
clip_threshold: 0.28
