run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.5
same_latent: false
style: "A photo of "
subject: "a asian man"
concept_token: 
  - "asian man"
settings:
  - "in a luxuary hotel"
  - "in a luxuary motel"
  - "in a jazz bar"
cache_cpu_offloading: false
out_dir: "out"
clip_threshold: 0.28
