run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "an young white man"
concept_token:
  - "young white man"
  - "short hair"
settings:
  - "with short hair wearing hiking clothes and a backpack on a forest mountain trail."
  - "with short hair wearing a helmet and cycling attire on a riverside bike path."
  - "with short hair wearing an outdoor jacket and comfortable pants at a campsite near a campfire."
  - "with short hair wearing a life vest and athletic bottoms by a kayak rental area."
  - "with short hair wearing running shoes and workout clothes on a riverside running track."
  - "with short hair wearing a soccer uniform on a park field with a visible goalpost."
  - "with short hair wearing ski gear on a snowy slope with a ski lift in the background"
out_dir: "condition_4"
clip_threshold: 0.28
