run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "an young white man"
concept_token:
  - "youn white man"
  - "short hair"
settings:
  - "with short hair, wearing a volunteer T-shirt in an animal shelter."
  - "with short hair, wearing gloves at a park cleanup."
  - "with short hair, wearing an apron at a free meal service."
  - "with short hair, wearing casual clothes in a blood donation center."
  - "with short hair, wearing a volunteer badge at a community center."
out_dir: "condition_3" 
clip_threshold: 0.28
