run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "a white man"
concept_token:
  - "white man"
  - "30 years olds"
  - "short hair" 
settings:
  - "who is 30 years old, with short hair, wearing a formal suit in a bright gray studio."
  - "who is 30 years old, with short hair, wearing a blazer and blouse in a minimalist office."
  - "who is 30 years old, with short hair, wearing a formal suit in a modern corridor."
  - "who is 30 years old, with short hair, wearing a dark-toned suit in a dimly lit studio."
out_dir: "condition_1"
clip_threshold: 0.29
