run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing workout attire, standing in gym"
      - "who is 30 years old, with short hair, wearing casual clothes, sitting comfortably on a park bench"
      - "who is 30 years old, with short hair, wearing casual attire, relaxing on a bench in the park"
      - "who is 30 years old, with short hair, wearing comfortable outfit, seated on a park bench"
      - "who is 30 years old, with short hair, wearing casual wear, resting on a bench outdoors"
      - "who is 30 years old, with short hair, wearing leisure clothes, sitting peacefully in park"
      - "who is 30 years old, with short hair, wearing informal attire, on bench in green space"
      - "who is 30 years old, with short hair, wearing relaxed clothing, seated in public park"
      - "who is 30 years old, with short hair, wearing everyday clothes, on park seating area"
      - "who is 30 years old, with short hair, wearing casual garments, resting on outdoor bench"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing casual outfit, lounging on park bench"
      - "who is 30 years old, with short hair, wearing comfortable clothes, seated in nature"
      - "who is 30 years old, with short hair, wearing relaxed attire, on bench surrounded by trees"
      - "who is 30 years old, with short hair, wearing casual wear, sitting in park environment"
      - "who is 30 years old, with short hair, wearing informal clothes, resting in outdoor setting"
      - "who is 30 years old, with short hair, wearing leisure attire, on bench in public garden"
      - "who is 30 years old, with short hair, wearing everyday outfit, seated in park scenery"
      - "who is 30 years old, with short hair, wearing comfortable garments, relaxing in green area"
      - "who is 30 years old, with short hair, wearing casual clothing, on bench in open space"
      - "who is 30 years old, with short hair, wearing relaxed wear, sitting amidst park greenery"

out_dir: "condition_3/3_park"
clip_threshold: 0.28
