run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, on a park bench"
      - "who is 30 years old, with short hair, wearing comfortable attire, on a bench in the park"
      - "who is 30 years old, with short hair, wearing relaxed outfit, on a bench along a park path"
      - "who is 30 years old, with short hair, wearing casual wear, on a bench along a park trail"
      - "who is 30 years old, with short hair, wearing leisure clothes, on a park bench"
      - "who is 30 years old, with short hair, wearing informal attire, on a bench in a park setting"
      - "who is 30 years old, with short hair, wearing everyday clothes, on a bench in a park walkway"
      - "who is 30 years old, with short hair, wearing comfortable garments, on a park bench near trees"
      - "who is 30 years old, with short hair, wearing relaxed attire, on a bench in a park's scenic spot"
      - "who is 30 years old, with short hair, wearing casual outfit, on a bench along a park's winding path"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothing, on a bench along a park trail"
      - "who is 30 years old, with short hair, wearing comfortable wear, on a park bench by a footpath"
      - "who is 30 years old, with short hair, wearing relaxed clothes, on a bench in a park's central area"
      - "who is 30 years old, with short hair, wearing informal outfit, on a bench in a park's quiet corner"
      - "who is 30 years old, with short hair, wearing leisure attire, on a park bench overlooking a garden"
      - "who is 30 years old, with short hair, wearing everyday garments, on a bench in a park's shaded area"
      - "who is 30 years old, with short hair, wearing casual wear, on a bench along a park's main pathway"
      - "who is 30 years old, with short hair, wearing comfortable clothing, at a park bench near flowers"
      - "who is 30 years old, with short hair, wearing relaxed attire, on a bench in a park's scenic spot"
      - "who is 30 years old, with short hair, wearing casual outfit, on a bench along a park's winding path"
  
  group_3:
    settings:
      - "who is 30 years old, with short hair, wearing informal attire, on a bench in a park setting"
      - "who is 30 years old, with short hair, wearing everyday clothes, on a bench in a park walkway"
      - "who is 30 years old, with short hair, wearing comfortable garments, on a park bench near trees"
      - "who is 30 years old, with short hair, wearing relaxed attire, on a bench in a park's scenic spot"
      - "who is 30 years old, with short hair, wearing casual outfit, on a bench along a park's winding path"

out_dir: "condition_3/3_park"
clip_threshold: 0.28
