run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, seated at a restaurant table"
      - "who is 30 years old, with short hair, in comfortable attire, at a cozy dining establishment"
      - "who is 30 years old, with short hair, dressed casually, in a modest restaurant setting"
      - "who is 30 years old, with short hair, in relaxed clothing, at a casual eatery"
      - "who is 30 years old, with short hair, wearing everyday clothes, in a simple dining venue"
      - "who is 30 years old, with short hair, in laid-back attire, at an unpretentious restaurant"
      - "who is 30 years old, with short hair, dressed down, in a homestyle dining atmosphere"
      - "who is 30 years old, with short hair, in comfortable wear, at a neighborhood restaurant"
      - "who is 30 years old, with short hair, casually dressed, in a family-style dining place"
      - "who is 30 years old, with short hair, in relaxed outfit, at a local eatery"
  group_2:
    settings:
      - "who is 30 years old, with short hair, in casual attire, seated for a meal at a restaurant"
      - "who is 30 years old, with short hair, wearing comfortable clothes, in a diner setting"
      - "who is 30 years old, with short hair, dressed informally, at a bistro table"
      - "who is 30 years old, with short hair, in everyday wear, at a casual dining spot"
      - "who is 30 years old, with short hair, wearing relaxed clothing, in a cafe-style restaurant"
      - "who is 30 years old, with short hair, in laid-back outfit, at a modest eatery"
      - "who is 30 years old, with short hair, casually dressed, in a simple restaurant interior"
      - "who is 30 years old, with short hair, in comfortable attire, at a local dining establishment"
      - "who is 30 years old, with short hair, wearing casual clothes, in a cozy restaurant atmosphere"
      - "who is 30 years old, with short hair, dressed down, at an unpretentious dining venue"

out_dir: "condition_3/4_restaurant"
clip_threshold: 0.28
