run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing casual attire, standing on the beach with ocean background"
      - "who is 30 years old, with short hair, in beachwear, posing by the ocean"
      - "who is 30 years old, with short hair, dressed casually, walking along the shoreline"
      - "who is 30 years old, with short hair, in relaxed clothing, enjoying the ocean view"
      - "who is 30 years old, with short hair, wearing summer outfit, with waves in the background"
      - "who is 30 years old, with short hair, in beach-appropriate attire, near the ocean"
      - "who is 30 years old, with short hair, casually dressed, looking out at the sea"
      - "who is 30 years old, with short hair, in laid-back clothes, on sandy beach with ocean backdrop"
      - "who is 30 years old, with short hair, wearing comfortable beach attire, by the ocean"
      - "who is 30 years old, with short hair, in casual beachwear, with ocean scenery"
  group_2:
    settings:
      - "who is 30 years old, with short hair, in casual beach outfit, standing near ocean waves"
      - "who is 30 years old, with short hair, wearing relaxed attire, at oceanfront"
      - "who is 30 years old, with short hair, dressed for the beach, with ocean in background"
      - "who is 30 years old, with short hair, in summer clothing, enjoying ocean breeze"
      - "who is 30 years old, with short hair, casually dressed, on beach with ocean view"
      - "who is 30 years old, with short hair, in beachwear, watching the ocean"
      - "who is 30 years old, with short hair, wearing casual clothes, near crashing waves"
      - "who is 30 years old, with short hair, in comfortable attire, by the seaside"
      - "who is 30 years old, with short hair, dressed casually, with ocean horizon"
      - "who is 30 years old, with short hair, in beach-ready outfit, facing the ocean"

out_dir: "condition_3/5_ocean"
clip_threshold: 0.28
