run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, sitting comfortably on a couch at home"
      - "who is 30 years old, with short hair, wearing casual attire, relaxing in a living room chair"
      - "who is 30 years old, with short hair, wearing casual clothes, seated at a dining table at home"
      - "who is 30 years old, with short hair, wearing comfortable clothes, sitting cross-legged on the floor"
      - "who is 30 years old, with short hair, wearing a t-shirt and jeans, lounging in an armchair"
      - "who is 30 years old, with short hair, wearing casual wear, sitting at a home office desk"
      - "who is 30 years old, with short hair, wearing informal clothes, seated on a window seat at home"
      - "who is 30 years old, with short hair, wearing relaxed clothing, sitting on a kitchen stool"
      - "who is 30 years old, with short hair, wearing casual attire, seated on a porch swing"
      - "who is 30 years old, with short hair, wearing comfortable outfit, sitting in a beanbag chair"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, sitting on a bed with pillows"
      - "who is 30 years old, with short hair, wearing a sweater, seated at a breakfast nook"
      - "who is 30 years old, with short hair, wearing casual wear, sitting on steps inside the house"
      - "who is 30 years old, with short hair, wearing comfortable clothes, seated in a rocking chair"
      - "who is 30 years old, with short hair, wearing relaxed attire, sitting at a home bar"
      - "who is 30 years old, with short hair, wearing lounge clothes, seated on a window ledge"
      - "who is 30 years old, with short hair, wearing casual outfit, sitting in a reading nook"
      - "who is 30 years old, with short hair, wearing informal clothes, seated at a hobby desk"
      - "who is 30 years old, with short hair, wearing comfortable clothing, sitting on a floor cushion"
      - "who is 30 years old, with short hair, wearing casual attire, seated in a hanging chair"

out_dir: "condition_3/2_house"
clip_threshold: 0.28
