run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "${HAIR_CONCEPT}"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing beside plain wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, posing near blank wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing straight by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing comfortably by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, leaning slightly on wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, facing camera near wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing relaxed by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, posing casually by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing still near wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, positioned beside wall"
  group_2:
    settings:
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing comfortably by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, leaning slightly on wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing upright near wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, posed against plain wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing calmly by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, positioned near blank wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing quietly by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, posing simply near wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing at ease by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, positioned naturally by wall"
  group_3:
    settings:
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, positioned near blank wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing quietly by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, posing simply near wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, standing at ease by wall"
      - "who is 30 years old, with ${HAIR_CONCEPT}, wearing casual clothes, positioned naturally by wall"

out_dir: "condition_3/1_wall"
clip_threshold: 0.28
