run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal at a restaurant table"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a cozy dining establishment"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a modest restaurant setting"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a casual eatery"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a simple dining venue"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in an unpretentious restaurant"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a homestyle dining atmosphere"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a neighborhood restaurant"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a family-style dining place"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a local eatery"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a restaurant"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a diner setting"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal at a bistro table"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a casual dining spot"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a cafe-style restaurant"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a modest eatery"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a simple restaurant interior"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a local dining establishment"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a cozy restaurant atmosphere"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in an unpretentious dining venue"
  group_3:
    settings:
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in an unpretentious restaurant"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a homestyle dining atmosphere"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a neighborhood restaurant"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a family-style dining place"
      - "who is 30 years old, with short hair, wearing casual clothes, eating meal in a local eatery"

out_dir: "condition_3/4_restaurant"
clip_threshold: 0.28
