run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing a comfortable hoodie while working in a home office"
      - "who is 30 years old, with short hair, sporting a casual hoodie at their home workspace"
      - "who is 30 years old, with short hair, in a cozy hoodie, seated at a home office desk"
      - "who is 30 years old, with short hair, donning a relaxed hoodie in their home study"
      - "who is 30 years old, with short hair, wearing a laid-back hoodie while remote working"
      - "who is 30 years old, with short hair, in a casual hoodie at their home workstation"
      - "who is 30 years old, with short hair, sporting a comfortable hoodie in a residential office setup"
      - "who is 30 years old, with short hair, wearing a hoodie while working from their home desk"
      - "who is 30 years old, with short hair, in a relaxed hoodie at their home office corner"
      - "who is 30 years old, with short hair, donning a casual hoodie in their home workspace"
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing a hoodie during a virtual meeting from home"
      - "who is 30 years old, with short hair, in a comfortable hoodie at their home office setup"
      - "who is 30 years old, with short hair, sporting a casual hoodie while working remotely"
      - "who is 30 years old, with short hair, donning a hoodie in their residential workspace"
      - "who is 30 years old, with short hair, wearing a relaxed hoodie at their home desk area"
      - "who is 30 years old, with short hair, in a laid-back hoodie during home office hours"
      - "who is 30 years old, with short hair, sporting a hoodie in their home study environment"
      - "who is 30 years old, with short hair, wearing a casual hoodie at their remote workspace"
      - "who is 30 years old, with short hair, in a comfortable hoodie while home-based working"
      - "who is 30 years old, with short hair, donning a hoodie at their residential office desk"

out_dir: "condition_2/2"
clip_threshold: 0.28
