run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, discussing with colleagues, in meeting room."
      - "who is 30 years old, with short hair, conversing in team huddle, in office setting."
      - "who is 30 years old, with short hair, engaged in group talk, in conference room."
      - "who is 30 years old, with short hair, participating in team discussion, in meeting space."
      - "who is 30 years old, with short hair, interacting in business meeting, in boardroom."
      - "who is 30 years old, with short hair, communicating ideas, corporate gathering."
      - "who is 30 years old, with short hair, collaborating in project meeting, in office."
      - "who is 30 years old, with short hair, exchanging thoughts, in team briefing room."
      - "who is 30 years old, with short hair, brainstorming with coworkers, in meeting area."
      - "who is 30 years old, with short hair, presenting to team, in conference setting."
  group_2:
    settings:
      - "who is 30 years old, with short hair, leading discussion, in office meeting room."
      - "who is 30 years old, with short hair, sharing insights, in team roundtable."
      - "who is 30 years old, with short hair, networking in corporate event, in meeting hall."
      - "who is 30 years old, with short hair, debating ideas, in business conference room."
      - "who is 30 years old, with short hair, facilitating group dialogue, in office space."
      - "who is 30 years old, with short hair, engaging in team conversation, in meeting setup."
      - "who is 30 years old, with short hair, contributing to group discussion, in boardroom."
      - "who is 30 years old, with short hair, participating in strategy meeting, in office."
      - "who is 30 years old, with short hair, addressing colleagues, in conference area."
      - "who is 30 years old, with short hair, collaborating in team session, in meeting room."

out_dir: "condition_2/4_meeting"
clip_threshold: 0.28
