run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, analyzing whiteboard content."
      - "who is 30 years old, with short hair, studying whiteboard notes."
      - "who is 30 years old, with short hair, pondering whiteboard ideas."
      - "who is 30 years old, with short hair, examining whiteboard diagrams."
      - "who is 30 years old, with short hair, contemplating whiteboard info."
      - "who is 30 years old, with short hair, focusing on whiteboard data."
      - "who is 30 years old, with short hair, interpreting whiteboard text."
      - "who is 30 years old, with short hair, reflecting on whiteboard concepts."
      - "who is 30 years old, with short hair, assessing whiteboard details."
      - "who is 30 years old, with short hair, considering whiteboard points."
  group_2:
    settings:
      - "who is 30 years old, with short hair, scrutinizing whiteboard content."
      - "who is 30 years old, with short hair, absorbing whiteboard info."
      - "who is 30 years old, with short hair, decoding whiteboard notes."
      - "who is 30 years old, with short hair, processing whiteboard data."
      - "who is 30 years old, with short hair, evaluating whiteboard ideas."
      - "who is 30 years old, with short hair, reviewing whiteboard text."
      - "who is 30 years old, with short hair, comprehending whiteboard concepts."
      - "who is 30 years old, with short hair, observing whiteboard diagrams."
      - "who is 30 years old, with short hair, deliberating whiteboard points."
      - "who is 30 years old, with short hair, studying whiteboard details."

out_dir: "condition_2/5_whiteboard"
clip_threshold: 0.28
