run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing white shirt, holding mic, in a presentation setting."
      - "who is 30 years old, with short hair, wearing white shirt, using microphone, in a public speaking event."
      - "who is 30 years old, with short hair, wearing white shirt, gripping mic, in a conference talk."
      - "who is 30 years old, with short hair, wearing white shirt, speaking into microphone, in a seminar."
      - "who is 30 years old, with short hair, wearing white shirt, adjusting mic, in a lecture scenario."
      - "who is 30 years old, with short hair, wearing white shirt, gesturing with mic, in a keynote address."
      - "who is 30 years old, with short hair, wearing white shirt, presenting with microphone, in a business meeting."
      - "who is 30 years old, with short hair, wearing white shirt, handling mic, in a panel discussion."
      - "who is 30 years old, with short hair, wearing white shirt, amplifying voice with mic, in a workshop."
      - "who is 30 years old, with short hair, wearing white shirt, addressing audience with microphone, in a symposium."
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing white shirt, positioning mic stand, in a stage presentation."
      - "who is 30 years old, with short hair, wearing white shirt, carrying wireless mic, in a TED-style talk."
      - "who is 30 years old, with short hair, wearing white shirt, answering questions with mic, in a Q&A session."
      - "who is 30 years old, with short hair, wearing white shirt, emphasizing points with mic, in a corporate briefing."
      - "who is 30 years old, with short hair, wearing white shirt, wearing lapel mic, in a product launch."
      - "who is 30 years old, with short hair, wearing white shirt, speaking through headset mic, in a motivational speech."
      - "who is 30 years old, with short hair, wearing white shirt, moderating with tabletop mic, in a roundtable discussion."
      - "who is 30 years old, with short hair, wearing white shirt, leaning into podium mic, in a formal address."
      - "who is 30 years old, with short hair, wearing white shirt, passing handheld mic, in an interactive presentation."
      - "who is 30 years old, with short hair, wearing white shirt, concluding speech with mic, in a closing ceremony."

out_dir: "condition_2/1_presentation"
clip_threshold: 0.28
