run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "${HAIR_CONCEPT}"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a corporate office."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers at a workstation."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers at a desk."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a modern office."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in an office."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers at an executive desk."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a business center."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a workspace."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers at an office desk."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in an office."
  group_2:
    settings:
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers at an office desk."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in an office."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a co-working space."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in an office."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers at a conference table."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in an open-plan office."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a startup office."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a business center."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers at a workstation."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in an office."
  group_3:
    settings:
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a meeting room."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a home office."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a creative studio."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in a collaborative space."
      - "who is 30 years old with ${HAIR_CONCEPT}, holding papers in an office."

out_dir: "condition_2/2_paper"
clip_threshold: 0.28
