run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old with short hair, at a desk with documents in a brightly lit corporate office."
      - "who is 30 years old with short hair, at a workstation with documents, surrounded by monitors and office supplies."
      - "who is 30 years old with short hair, with papers at a large wooden desk in a formal corporate office with shelves in the background."
      - "who is 30 years old with short hair, with documents at a clean and organized desk in a modern office setting."
      - "who is 30 years old with short hair, with papers in a minimalist office with large windows letting in natural light."
      - "who is 30 years old with short hair, at an executive desk with polished furniture and documents."
      - "who is 30 years old with short hair, in a small office cubicle with papers, surrounded by pinned memos and a desktop computer."
      - "who is 30 years old with short hair, with documents at a corporate workspace filled with neatly arranged desks and coworkers in the background."
      - "who is 30 years old with short hair, at a tidy office desk with documents, a laptop, and stationery."
      - "who is 30 years old with short hair, in a busy office setting with documents under bright fluorescent lights."
  group_2:
    settings:
      - "who is 30 years old with short hair, at a wooden desk with documents in a cozy home office with a small plant and a coffee mug."
      - "who is 30 years old with short hair, with documents in a well-organized professional office space with sleek modern decor."
      - "who is 30 years old with short hair, with documents while seated at a large table in a bright co-working space."
      - "who is 30 years old with short hair, with papers in a formal office environment with leather chairs and a large bookshelf."
      - "who is 30 years old with short hair, at a conference table with documents under warm lighting."
      - "who is 30 years old with short hair, at a desk with papers in an open-plan office with coworkers working in the background."
      - "who is 30 years old with short hair, at a startup office desk with documents, surrounded by whiteboards and brainstorming notes."
      - "who is 30 years old with short hair, with papers in a business center with clean white walls and a modern glass table."
      - "who is 30 years old with short hair, with documents in an organized workstation with a desktop monitor and neat files."
      - "who is 30 years old with short hair, in a sleek office interior with minimalist decor and documents."

out_dir: "condition_2/2_paper"
clip_threshold: 0.28
