run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing business casual attire near a whiteboard in a co-working space"
      - "who is 30 years old, with short hair, in smart casual wear presenting at a shared workspace"
      - "who is 30 years old, with short hair, sporting business casual clothes at a collaborative office"
      - "who is 30 years old, with short hair, wearing professional casual attire in a modern co-working environment"
      - "who is 30 years old, with short hair, in business casual dress beside a whiteboard at a shared office"
      - "who is 30 years old, with short hair, donning smart casual clothing in a co-working setup"
      - "who is 30 years old, with short hair, wearing business casual near a presentation board"
      - "who is 30 years old, with short hair, in professional casual wear at a shared workplace"
      - "who is 30 years old, with short hair, sporting smart casual attire in a collaborative space"
      - "who is 30 years old, with short hair, wearing business casual by a whiteboard wall"
  group_2:
    settings:
      - "who is 30 years old, with short hair, in business casual at a modern co-working hub"
      - "who is 30 years old, with short hair, wearing smart casual during a whiteboard session"
      - "who is 30 years old, with short hair, sporting professional casual in a shared office space"
      - "who is 30 years old, with short hair, in business casual attire at a collaborative workspace"
      - "who is 30 years old, with short hair, wearing smart casual near an office whiteboard"
      - "who is 30 years old, with short hair, donning business casual in a co-working environment"
      - "who is 30 years old, with short hair, in professional casual at a shared office setup"
      - "who is 30 years old, with short hair, wearing business casual beside a presentation area"
      - "who is 30 years old, with short hair, sporting smart casual in a modern workspace"
      - "who is 30 years old, with short hair, in business casual near a collaborative board"

out_dir: "condition_2/5"
clip_threshold: 0.28
