run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a convention center."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a conference room."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in an auditorium."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a lecture hall."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a forum."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a presentation room."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a meeting room."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a briefing room."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a workshop space."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a boardroom."
  group_2:
    settings:
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in an amphitheater."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a convention center."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a forum."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a briefing room."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in an event hall."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a lecture theater."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a conference hall."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in an assembly hall."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a symposium venue."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a workshop space."
  group_3:
    settings:
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a workshop space."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in an executive suite."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a forum."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a presentation room."
      - "who is 30 years old, with short hair, wearing white shirt, holding mic for presentation, in a large hall."

out_dir: "condition_2/1_presentation"
clip_threshold: 0.28
