run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "${PERSON_CONCEPT}"
concept_token:
  - "${PERSON_CONCEPT}"
  - "30 years olds"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, focused on a laptop screen, at a bustling cafe."
      - "who is 30 years old, with short hair, typing on a notebook computer, in a cozy coffee shop."
      - "who is 30 years old, with short hair, working intently on a laptop, at a trendy cafe corner."
      - "who is 30 years old, with short hair, engrossed in their laptop display, at a modern coffee house."
      - "who is 30 years old, with short hair, scrolling through a laptop, at a quiet cafe table."
      - "who is 30 years old, with short hair, studying information on a laptop screen, in a cafe ambiance."
      - "who is 30 years old, with short hair, deeply concentrated on their laptop, at a busy coffee shop."
      - "who is 30 years old, with short hair, reading from a laptop display, in a serene cafe setting."
      - "who is 30 years old, with short hair, analyzing data on a laptop, at a hip coffee bar."
      - "who is 30 years old, with short hair, immersed in laptop work, at a charming neighborhood cafe."
  group_2:
    settings:
      - "who is 30 years old, with short hair, attending a virtual meeting via laptop, in a cafe environment."
      - "who is 30 years old, with short hair, writing code on a laptop, at a sunlit cafe window seat."
      - "who is 30 years old, with short hair, reviewing documents on a laptop screen, at a cafe patio."
      - "who is 30 years old, with short hair, participating, in an online discussion through their laptop, at a cafe."
      - "who is 30 years old, with short hair, editing a presentation on their laptop, in a coffee shop atmosphere."
      - "who is 30 years old, with short hair, researching on a laptop, at a cafe study nook."
      - "who is 30 years old, with short hair, collaborating remotely via laptop, in a vibrant cafe setting."
      - "who is 30 years old, with short hair, designing on a laptop, at an artisanal coffee shop."
      - "who is 30 years old, with short hair, managing emails on a laptop screen, at a quaint cafe."
      - "who is 30 years old, with short hair, video conferencing on a laptop, in a lively coffee house."

out_dir: "condition_2/3_cafe_laptop"
clip_threshold: 0.28
