run_type: batch
gpu: 0
seed: 40
mask_dropout: 0.4
same_latent: false
style: "A photo of"
subject: "good-looking ${PERSON_CONCEPT}"
concept_token:
  - "good-looking"
  - "${PERSON_CONCEPT}"
  - "30 years old"
  - "short hair"

settings_groups:
  group_1:
    settings:
      - "who is 30 years old, with short hair, typing on a laptop, at a bustling cafe."
      - "who is 30 years old, with short hair, typing on a laptop, in a cozy coffee shop."
      - "who is 30 years old, with short hair, typing on a laptop, at a cafe patio."
      - "who is 30 years old, with short hair, typing on a laptop, at a cafe."
      - "who is 30 years old, with short hair, typing on a laptop, in a coffee shop atmosphere."
      - "who is 30 years old, with short hair, typing on a laptop, in a cafe ambiance."
      - "who is 30 years old, with short hair, typing on a laptop, at a coffee shop."
      - "who is 30 years old, with short hair, typing on a laptop, in a serene cafe setting."
      - "who is 30 years old, with short hair, typing on a laptop, at a coffee bar."
      - "who is 30 years old, with short hair, typing on a laptop, at a charming cafe."
  group_2:
    settings:
      - "who is 30 years old, with short hair, typing on a laptop, in a cafe environment."
      - "who is 30 years old, with short hair, typing on a laptop, at a sunlit cafe window seat."
      - "who is 30 years old, with short hair, typing on a laptop, at a cafe patio."
      - "who is 30 years old, with short hair, typing on a laptop, at a cafe."
      - "who is 30 years old, with short hair, typing on a laptop, in a coffee shop atmosphere."
      - "who is 30 years old, with short hair, typing on a laptop, at a cafe study nook."
      - "who is 30 years old, with short hair, typing on a laptop, in a vibrant cafe setting."
      - "who is 30 years old, with short hair, typing on a laptop, at an artisanal coffee shop."
      - "who is 30 years old, with short hair, typing on a laptop, at a quaint cafe."
      - "who is 30 years old, with short hair, typing on a laptop, in a coffee house."
  group_3:
    settings:
      - "who is 30 years old, with short hair, typing on a laptop, at a cozy cafe."
      - "who is 30 years old, with short hair, typing on a laptop, in a coffee shop."
      - "who is 30 years old, with short hair, typing on a laptop, at an outdoor cafe terrace."
      - "who is 30 years old, with short hair, typing on a laptop, in a minimalist coffee bar."
      - "who is 30 years old, with short hair, typing on a laptop, at a vintage-themed cafe."

out_dir: "condition_2/3_cafe_laptop"
clip_threshold: 0.28
